name: Build images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build
      run: |
        docker login -u legoktm -p ${{ secrets.DOCKER_HUB_ACCESS }}
        ./build.py --push
