name: Build images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        name:
          - "auto-dch:latest"
          - "dput:latest"
          - "build-deb:debian-unstable"
          - "build-deb:debian-bullseye"
          - "build-deb:debian-buster"
          - "build-deb:ubuntu-jammy"
          - "build-deb:ubuntu-impish"
          - "build-deb:ubuntu-hirsute"
          - "build-deb:ubuntu-focal"
          - "build-deb:ubuntu-bionic"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Build
      run: |
        docker login -u legoktm -p ${{ secrets.DOCKER_HUB_ACCESS }}
        ./build.py ${{ matrix.name }} --push
